//
//  CategoryEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension CategoryEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<CategoryEntity> {
        return NSFetchRequest<CategoryEntity>(entityName: "CategoryEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var iconName: String?
    @NSManaged public var colorHex: String?
    @NSManaged public var sortOrder: Int16

}

extension CategoryEntity : Identifiable {

}
