//
//  CategoryEntity+CoreDataClass.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

@objc(CategoryEntity)
public class CategoryEntity: NSManagedObject {

}
