//
//  ExpirationTrackerEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension ExpirationTrackerEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ExpirationTrackerEntity> {
        return NSFetchRequest<ExpirationTrackerEntity>(entityName: "ExpirationTrackerEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var purchaseDate: Date?
    @NSManaged public var expirationDate: Date?
    @NSManaged public var estimatedExpirationDate: Date?
    @NSManaged public var quantity: NSDecimalNumber?
    @NSManaged public var remainingQuantity: NSDecimalNumber?
    @NSManaged public var storageLocation: String?
    @NSManaged public var isConsumed: Bool
    @NSManaged public var consumedAt: Date?
    @NSManaged public var isWasted: Bool
    @NSManaged public var wastedAt: Date?
    @NSManaged public var groceryItem: GroceryItemEntity?
    @NSManaged public var purchase: PurchaseEntity?

}

extension ExpirationTrackerEntity : Identifiable {

}
