//
//  ExpirationTrackerEntity+CoreDataClass.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

@objc(ExpirationTrackerEntity)
public class ExpirationTrackerEntity: NSManagedObject {

}
