//
//  GroceryItemEntity+CoreDataClass.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

@objc(GroceryItemEntity)
public class GroceryItemEntity: NSManagedObject {

}
