//
//  GroceryItemEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension GroceryItemEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<GroceryItemEntity> {
        return NSFetchRequest<GroceryItemEntity>(entityName: "GroceryItemEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var categoryName: String?
    @NSManaged public var brand: String?
    @NSManaged public var unit: String?
    @NSManaged public var notes: String?
    @NSManaged public var imageData: Data?
    @NSManaged public var averagePrice: NSDecimalNumber?
    @NSManaged public var createdAt: Date?
    @NSManaged public var updatedAt: Date?
    @NSManaged public var purchases: NSSet?
    @NSManaged public var shoppingListItems: NSSet?
    @NSManaged public var expirationTrackers: NSSet?
    @NSManaged public var priceHistory: NSSet?

}

// MARK: Generated accessors for purchases
extension GroceryItemEntity {

    @objc(addPurchasesObject:)
    @NSManaged public func addToPurchases(_ value: PurchaseEntity)

    @objc(removePurchasesObject:)
    @NSManaged public func removeFromPurchases(_ value: PurchaseEntity)

    @objc(addPurchases:)
    @NSManaged public func addToPurchases(_ values: NSSet)

    @objc(removePurchases:)
    @NSManaged public func removeFromPurchases(_ values: NSSet)

}

// MARK: Generated accessors for shoppingListItems
extension GroceryItemEntity {

    @objc(addShoppingListItemsObject:)
    @NSManaged public func addToShoppingListItems(_ value: ShoppingListItemEntity)

    @objc(removeShoppingListItemsObject:)
    @NSManaged public func removeFromShoppingListItems(_ value: ShoppingListItemEntity)

    @objc(addShoppingListItems:)
    @NSManaged public func addToShoppingListItems(_ values: NSSet)

    @objc(removeShoppingListItems:)
    @NSManaged public func removeFromShoppingListItems(_ values: NSSet)

}

// MARK: Generated accessors for expirationTrackers
extension GroceryItemEntity {

    @objc(addExpirationTrackersObject:)
    @NSManaged public func addToExpirationTrackers(_ value: ExpirationTrackerEntity)

    @objc(removeExpirationTrackersObject:)
    @NSManaged public func removeFromExpirationTrackers(_ value: ExpirationTrackerEntity)

    @objc(addExpirationTrackers:)
    @NSManaged public func addToExpirationTrackers(_ values: NSSet)

    @objc(removeExpirationTrackers:)
    @NSManaged public func removeFromExpirationTrackers(_ values: NSSet)

}

// MARK: Generated accessors for priceHistory
extension GroceryItemEntity {

    @objc(addPriceHistoryObject:)
    @NSManaged public func addToPriceHistory(_ value: PriceHistoryEntity)

    @objc(removePriceHistoryObject:)
    @NSManaged public func removeFromPriceHistory(_ value: PriceHistoryEntity)

    @objc(addPriceHistory:)
    @NSManaged public func addToPriceHistory(_ values: NSSet)

    @objc(removePriceHistory:)
    @NSManaged public func removeFromPriceHistory(_ values: NSSet)

}

extension GroceryItemEntity : Identifiable {

}
