//
//  PriceHistoryEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension PriceHistoryEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<PriceHistoryEntity> {
        return NSFetchRequest<PriceHistoryEntity>(entityName: "PriceHistoryEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var price: NSDecimalNumber?
    @NSManaged public var recordedAt: Date?
    @NSManaged public var storeName: String?
    @NSManaged public var source: String?
    @NSManaged public var groceryItem: GroceryItemEntity?

}

extension PriceHistoryEntity : Identifiable {

}
