//
//  PurchaseEntity+CoreDataClass.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

@objc(PurchaseEntity)
public class PurchaseEntity: NSManagedObject {

}
