//
//  PurchaseEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension PurchaseEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<PurchaseEntity> {
        return NSFetchRequest<PurchaseEntity>(entityName: "PurchaseEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var quantity: NSDecimalNumber?
    @NSManaged public var price: NSDecimalNumber?
    @NSManaged public var totalCost: NSDecimalNumber?
    @NSManaged public var purchaseDate: Date?
    @NSManaged public var storeName: String?
    @NSManaged public var receiptImage: Data?
    @NSManaged public var groceryItem: GroceryItemEntity?
    @NSManaged public var expirationTracker: ExpirationTrackerEntity?

}

extension PurchaseEntity : Identifiable {

}
