//
//  ShoppingListItemEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension ShoppingListItemEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ShoppingListItemEntity> {
        return NSFetchRequest<ShoppingListItemEntity>(entityName: "ShoppingListItemEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var quantity: NSDecimalNumber?
    @NSManaged public var estimatedPrice: NSDecimalNumber?
    @NSManaged public var isPurchased: Bool
    @NSManaged public var purchasedAt: Date?
    @NSManaged public var actualPrice: NSDecimalNumber?
    @NSManaged public var shoppingList: ShoppingListEntity?
    @NSManaged public var groceryItem: GroceryItemEntity?

}

extension ShoppingListItemEntity : Identifiable {

}
