//
//  ShoppingListItemEntity+CoreDataClass.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

@objc(ShoppingListItemEntity)
public class ShoppingListItemEntity: NSManagedObject {

}
