//
//  ShoppingListEntity+CoreDataProperties.swift
//  Grocery-budget-optimizer
//
//  Auto-generated by Core Data model
//

import Foundation
import CoreData

extension ShoppingListEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<ShoppingListEntity> {
        return NSFetchRequest<ShoppingListEntity>(entityName: "ShoppingListEntity")
    }

    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var budgetAmount: NSDecimalNumber?
    @NSManaged public var createdAt: Date?
    @NSManaged public var updatedAt: Date?
    @NSManaged public var isCompleted: Bool
    @NSManaged public var completedAt: Date?
    @NSManaged public var items: NSSet?

}

// MARK: Generated accessors for items
extension ShoppingListEntity {

    @objc(addItemsObject:)
    @NSManaged public func addToItems(_ value: ShoppingListItemEntity)

    @objc(removeItemsObject:)
    @NSManaged public func removeFromItems(_ value: ShoppingListItemEntity)

    @objc(addItems:)
    @NSManaged public func addToItems(_ values: NSSet)

    @objc(removeItems:)
    @NSManaged public func removeFromItems(_ values: NSSet)

}

extension ShoppingListEntity : Identifiable {

}
